# Generated by Django 5.0 on 2023-12-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estufa', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=4, max_digits=8)),
                ('Fazenda', models.CharField(max_length=50)),
            ],
        ),
    ]
