# Generated by Django 5.0 on 2023-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criada", models.DateTimeField(verbose_name="Data de criação")),
                (
                    "data_atualizado",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da aplicação"
                    ),
                ),
                ("produto", models.CharField(max_length=50, verbose_name="Produto")),
                ("codigo", models.IntegerField(verbose_name="Codigo")),
                (
                    "descricao",
                    models.CharField(max_length=50, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="FichaDeAplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criada", models.DateTimeField(auto_now_add=True)),
                ("data_planejada", models.DateTimeField()),
                ("data_aplicada", models.DateTimeField()),
                ("atividade_id", models.PositiveIntegerField()),
                ("estufa_id", models.PositiveIntegerField()),
                ("produto_id", models.PositiveIntegerField()),
                ("irrigador_id", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoIrrigador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_tipo", models.CharField(max_length=50)),
            ],
        ),
    ]
