# Generated by Django 5.0 on 2023-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_atividade_fichadeaplicacao_produtos_tipoirrigador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estufa",
            name="area",
            field=models.FloatField(),
        ),
    ]
