# Generated by Django 4.2.9 on 2024-08-05 13:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0002_atividade_fichadeaplicacao_produtos_tipoirrigador"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="atividade_id",
        ),
    ]
