# Generated by Django 5.0 on 2023-12-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_alter_estufa_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estufa",
            name="area",
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
