# Generated by Django 4.2.9 on 2024-08-05 14:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_produtos_remove_estufa_fazenda_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="data_planejada",
        ),
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="estufa_id",
        ),
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="irrigador_id",
        ),
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="produto_id",
        ),
        migrations.AddField(
            model_name="atividade",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="atividade",
            name="data_atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Data da aplicação"),
        ),
        migrations.AddField(
            model_name="atividade",
            name="data_criada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de criação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="area",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=8, verbose_name="Área"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="atividade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="todos.atividade",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="dados",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="data_atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Data da aplicação"),
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="estufa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="todos.estufa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="irrigador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="todos.tipoirrigador",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="obs",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="pendente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tipoirrigador",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="atividade",
            name="nome",
            field=models.CharField(max_length=10, verbose_name="Atividade"),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="area",
            field=models.DecimalField(
                decimal_places=4, max_digits=8, verbose_name="Área"
            ),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="Fazenda",
            field=models.CharField(max_length=50, verbose_name="fazenda"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_aplicada",
            field=models.DateField(verbose_name="Data real"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_criada",
            field=models.DateTimeField(verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="tipoirrigador",
            name="nome_tipo",
            field=models.CharField(max_length=50, verbose_name="Irrigador"),
        ),
    ]
