# Generated by Django 4.2.9 on 2024-08-05 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_produtos_remove_fichadeaplicacao_atividade_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estufa",
            name="nome_estufa",
            field=models.CharField(max_length=50, verbose_name="Estufa"),
        ),
    ]
