# Generated by Django 5.0 on 2023-12-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_alter_estufa_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="nome",
            field=models.CharField(max_length=10, verbose_name="Atividade"),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="Fazenda",
            field=models.CharField(max_length=50, verbose_name="Fazenda"),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="area",
            field=models.DecimalField(
                decimal_places=4, max_digits=8, verbose_name="Área"
            ),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="nome_estufa",
            field=models.CharField(max_length=50, verbose_name="Estufa"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="atividade_id",
            field=models.PositiveIntegerField(verbose_name="Atividade associada"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_aplicada",
            field=models.DateTimeField(verbose_name="Data real"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_criada",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_planejada",
            field=models.DateTimeField(verbose_name="Data da aplicação"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="estufa_id",
            field=models.PositiveIntegerField(verbose_name="Estufa associada"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="irrigador_id",
            field=models.PositiveIntegerField(verbose_name="Irrigador associado"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="produto_id",
            field=models.PositiveIntegerField(verbose_name="Produto associado"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="codigo",
            field=models.IntegerField(verbose_name="Codigo"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="descricao",
            field=models.CharField(max_length=100, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="nome_produto",
            field=models.CharField(max_length=30, verbose_name="Produto"),
        ),
        migrations.AlterField(
            model_name="tipoirrigador",
            name="nome_tipo",
            field=models.CharField(max_length=50, verbose_name="Irrigador"),
        ),
    ]
