# Generated by Django 5.0 on 2023-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_atividade_nome_alter_estufa_fazenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estufa',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoirrigador',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
