# Generated by Django 5.0 on 2024-01-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0006_atividade_ativo_estufa_ativo_produtos_ativo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="produto_id",
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="area",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=8, verbose_name="Área"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="dados",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
