# Generated by Django 5.0 on 2024-01-03 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0007_remove_fichadeaplicacao_produto_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="data_aplicada",
        ),
        migrations.RemoveField(
            model_name="fichadeaplicacao",
            name="data_planejada",
        ),
    ]
