# Generated by Django 5.0 on 2024-01-03 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0008_remove_fichadeaplicacao_data_aplicada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="data_aplicada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data real"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="data_planejada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da aplicação"
            ),
            preserve_default=False,
        ),
    ]
