# Generated by Django 5.0 on 2024-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0009_fichadeaplicacao_data_aplicada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_criada",
            field=models.DateTimeField(verbose_name="Data de criação"),
        ),
    ]
