# Generated by Django 5.0 on 2024-01-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0010_alter_fichadeaplicacao_data_criada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="atividade_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todos.atividade"
            ),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="estufa_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todos.estufa"
            ),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="irrigador_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todos.tipoirrigador"
            ),
        ),
    ]
