# Generated by Django 5.0 on 2024-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0011_alter_fichadeaplicacao_atividade_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_aplicada",
            field=models.DateField(verbose_name="Data real"),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_planejada",
            field=models.DateField(verbose_name="Data da aplicação"),
        ),
    ]
