# Generated by Django 5.0 on 2024-01-04 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0012_alter_fichadeaplicacao_data_aplicada_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichadeaplicacao",
            old_name="atividade_id",
            new_name="atividade",
        ),
        migrations.RenameField(
            model_name="fichadeaplicacao",
            old_name="estufa_id",
            new_name="estufa",
        ),
        migrations.RenameField(
            model_name="fichadeaplicacao",
            old_name="irrigador_id",
            new_name="irrigador",
        ),
    ]
