# Generated by Django 5.0 on 2024-01-04 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0013_rename_atividade_id_fichadeaplicacao_atividade_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produtos",
            old_name="nome_produto",
            new_name="produto",
        ),
    ]
