# Generated by Django 5.0 on 2024-01-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0014_rename_nome_produto_produtos_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
