# Generated by Django 5.0 on 2024-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0015_fichadeaplicacao_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tipoirrigador",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
