# Generated by Django 5.0 on 2024-01-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0016_alter_atividade_ativo_alter_estufa_ativo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
