# Generated by Django 5.0 on 2024-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0017_alter_produtos_ativo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fichadeaplicacao",
            old_name="data_planejada",
            new_name="data_atualizado",
        ),
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="pendente",
            field=models.BooleanField(default=False),
        ),
    ]
