# Generated by Django 5.0 on 2024-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "todos",
            "0018_rename_data_planejada_fichadeaplicacao_data_atualizado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_atualizado",
            field=models.DateField(null=True, verbose_name="Data da aplicação"),
        ),
    ]
