# Generated by Django 5.0 on 2024-01-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0019_alter_fichadeaplicacao_data_atualizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="fichadeaplicacao",
            name="obs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
