# Generated by Django 5.0 on 2024-01-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0020_fichadeaplicacao_obs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="descricao",
            field=models.CharField(max_length=50, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="produto",
            field=models.CharField(max_length=50, verbose_name="Produto"),
        ),
    ]
