# Generated by Django 5.0 on 2024-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0022_rename_fazenda_estufa_fazenda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estufa",
            name="fazenda",
            field=models.CharField(max_length=50, verbose_name="fazenda"),
        ),
    ]
