# Generated by Django 4.2.9 on 2024-01-29 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0023_alter_estufa_fazenda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_atualizado",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data da aplicação"
            ),
            preserve_default=False,
        ),
    ]
