# Generated by Django 4.2.9 on 2024-01-30 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0024_alter_fichadeaplicacao_data_atualizado"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="data_atualizado",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da aplicação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="atividade",
            name="data_criada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de criação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estufa",
            name="data_atualizado",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da aplicação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="estufa",
            name="data_criada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de criação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produtos",
            name="data_atualizado",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data da aplicação"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produtos",
            name="data_criada",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de criação"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_atualizado",
            field=models.DateTimeField(verbose_name="Data da aplicação"),
        ),
    ]
