# Generated by Django 4.2.9 on 2024-02-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0025_atividade_data_atualizado_atividade_data_criada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="data_atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Data da aplicação"),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="data_atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Data da aplicação"),
        ),
        migrations.AlterField(
            model_name="estufa",
            name="data_criada",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Data da aplicação"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="data_atualizado",
            field=models.DateTimeField(auto_now=True, verbose_name="Data da aplicação"),
        ),
    ]
