# Generated by Django 4.2.9 on 2024-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0027_alter_produtos_data_criada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_criada",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
    ]
