# Generated by Django 4.2.9 on 2024-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0028_alter_fichadeaplicacao_data_criada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fichadeaplicacao",
            name="data_criada",
            field=models.DateTimeField(verbose_name="Data de criação"),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="data_criada",
            field=models.DateTimeField(verbose_name="Data de criação"),
        ),
    ]
