# Generated by Django 4.2.9 on 2024-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0030_alter_estufa_data_criada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="data_criada",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de criação"
            ),
        ),
    ]
