# Generated by Django 4.2.9 on 2024-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0031_alter_produtos_data_criada"),
    ]

    operations = [
        migrations.AddField(
            model_name="estufa",
            name="codigo",
            field=models.IntegerField(default=0, verbose_name="Codigo"),
            preserve_default=False,
        ),
    ]
